# Sigmoid 함수를 이용한 Perceptron 구현

In [9]:
import torch
import torch.nn as nn
import numpy as np

x_data = torch.FloatTensor([1.0, 2.0]) # x = (1, 2) 값 생성
print(x_data)

linear = nn.Linear(2, 1)  # y = (x_1w_1, x_2w_2) + b perceptron 생성
sigmoid = nn.Sigmoid()

z = sigmoid(linear(x_data))
print(z)

tensor([1., 2.])
tensor([0.7928], grad_fn=<SigmoidBackward0>)


In [10]:
print(linear.weight)
print(linear.bias)

Parameter containing:
tensor([[0.5754, 0.5017]], requires_grad=True)
Parameter containing:
tensor([-0.2370], requires_grad=True)


# Relu 함수를 이용한 Perceptron 구현

In [11]:
x_data= np.array([1.0, 2.0], dtype=np.float32)
x_data = torch.from_numpy(x_data)

linear = nn.Linear(2, 1)
relu = nn.ReLU()

z = relu(linear(x_data))

print(z)
print(linear.weight)
print(linear.bias)

tensor([0.9962], grad_fn=<ReluBackward0>)
Parameter containing:
tensor([[-0.3703,  0.4956]], requires_grad=True)
Parameter containing:
tensor([0.3754], requires_grad=True)


질문 : z 값이 1에 가까울수록 좋은건가?
